<a href="https://colab.research.google.com/github/Maniganiga404/python-practice/blob/main/Day24.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Day24
#pandas basics
# What is Pandas?
# Series
# DataFrame
# Creating data
# Columns
# Rows
# Indexing
# loc
# iloc
# Pandas is a Python library used for working with tabular data

In [2]:
#A Series is basically one column of data.
import pandas as pd

marks = pd.Series([85,72,36,97])

print(marks)

0    85
1    72
2    36
3    97
dtype: int64

In [3]:
print(marks[0])

85

In [7]:
#craeating a series with a custom index
import pandas as pd

marks = pd.Series([85,22,33],
                  index = ["Mani","Bhavi","Ani"])

print(marks)

Mani     85
Bhavi    22
Ani      33
dtype: int64

In [10]:
print(marks["Mani"])

85

In [12]:
#DataFrame
#DataFrame is basically a table

date = {
    "Name" : ["Mani","Bhavi"],
    "Age" : [24,17],
    "Marks" : [33,66]
}

df = pd.DataFrame(date)

print(df)

    Name  Age  Marks
0   Mani   24     33
1  Bhavi   17     66

In [14]:
print(df["Name"])

0     Mani
1    Bhavi
Name: Name, dtype: object

In [16]:
#Adding a new column
df["Passed"] = True

print(df)

    Name  Age  Marks  Passed
0   Mani   24     33    True
1  Bhavi   17     66    True

In [19]:
df["Bonus"] = df["Marks"]+5

print(df)

    Name  Age  Marks  Passed  Bonus
0   Mani   24     33    True     38
1  Bhavi   17     66    True     71

In [21]:
# loc is used to select data based on labels/index names.
df.loc[0]

Name      Mani
Age         24
Marks       33
Passed    True
Bonus       38
Name: 0, dtype: object

In [22]:
df.loc[1]

Name      Bhavi
Age          17
Marks        66
Passed     True
Bonus        71
Name: 1, dtype: object

In [23]:
df.loc[1,"Name"]

'Bhavi'

In [24]:
#iloc means integer-location based indexing
# his is VERY important for today.
# loc
# Uses labels:
# df.loc[1, "Marks"]
# iloc
# Uses positions:
# df.iloc[1, 2]

df.iloc[1]

Name      Bhavi
Age          17
Marks        66
Passed     True
Bonus        71
Name: 1, dtype: object

In [25]:
df.iloc[1,2]

np.int64(66)

In [27]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Manish", "Rahul", "Anu", "Kiran"],
    "Age": [20, 21, 19, 22],
    "Marks": [85, 91, 76, 88]
})

print(df)

     Name  Age  Marks
0  Manish   20     85
1   Rahul   21     91
2     Anu   19     76
3   Kiran   22     88

In [35]:
print(df["Marks"])

0    85
1    91
2    76
3    88
Name: Marks, dtype: int64

In [29]:
df.loc[2]

Name     Anu
Age       19
Marks     76
Name: 2, dtype: object

In [30]:
df.iloc[1,2]

np.int64(91)

In [32]:
df["Passed"] = True

print(df)

     Name  Age  Marks  Passed
0  Manish   20     85    True
1   Rahul   21     91    True
2     Anu   19     76    True
3   Kiran   22     88    True