<a href="https://colab.research.google.com/github/Maniganiga404/python-practice/blob/main/Day26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [129]:
#Day26
#Pandas Data cleaning

# Missing values (NaN)
# Finding missing values — isna(), isnull()
# Removing missing values — dropna()
# Filling missing values — fillna()
# Removing duplicate rows — drop_duplicates()
# Detecting duplicates
# Fixing incorrect data
# Changing data types — astype()
# String cleaning — .str

import pandas as pd

df = pd.DataFrame({
    "Name": ["Manish", "Rahul", "Anu", "Kiran"],
    "Age": [20, None, 19, 22],
    "Marks": [85, 91, None, 88]
})

print(df)

     Name   Age  Marks
0  Manish  20.0   85.0
1   Rahul   NaN   91.0
2     Anu  19.0    NaN
3   Kiran  22.0   88.0

In [130]:
#Finding missing values (isna)

print(df.isna())

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False

In [131]:
#Count missing values

print(df.isna().sum())

Name     0
Age      1
Marks    1
dtype: int64

In [132]:
import pandas as pd
df = pd.DataFrame({
    "Name" : ["Manish", "Rahul", "Anu", "Kiran", "Priya"],
    "Age" : [20, None,19,22,None],
    "Marks": [85, 91, None, 88, 95]
})

print(df)

     Name   Age  Marks
0  Manish  20.0   85.0
1   Rahul   NaN   91.0
2     Anu  19.0    NaN
3   Kiran  22.0   88.0
4   Priya   NaN   95.0

In [133]:
# 1. Print the DataFrame
# 2. Find which values are missing
# 3. Count the number of missing values in each column

print(df)

     Name   Age  Marks
0  Manish  20.0   85.0
1   Rahul   NaN   91.0
2     Anu  19.0    NaN
3   Kiran  22.0   88.0
4   Priya   NaN   95.0

In [134]:
print(df.isna())

    Name    Age  Marks
0  False  False  False
1  False   True  False
2  False  False   True
3  False  False  False
4  False   True  False

In [135]:
print(df.isna().sum())

Name     0
Age      2
Marks    1
dtype: int64

In [136]:
# Topic 2 — dropna()

print(df.dropna())

     Name   Age  Marks
0  Manish  20.0   85.0
3   Kiran  22.0   88.0

In [137]:
df.dropna(axis = 1)

     Name
0  Manish
1   Rahul
2     Anu
3   Kiran
4   Priya

In [138]:
#fillna()

df["Marks"] = df["Marks"].fillna(30)
df["Age"] = df["Age"].fillna(20)

print(df)

     Name   Age  Marks
0  Manish  20.0   85.0
1   Rahul  20.0   91.0
2     Anu  19.0   30.0
3   Kiran  22.0   88.0
4   Priya  20.0   95.0

In [139]:
#drop_duplicates()

df = df.drop_duplicates()

print(df)

     Name   Age  Marks
0  Manish  20.0   85.0
1   Rahul  20.0   91.0
2     Anu  19.0   30.0
3   Kiran  22.0   88.0
4   Priya  20.0   95.0

In [140]:
df = pd.DataFrame({
    "Name": ["Manish", "Rahul", "Manish", "Anu"],
    "Age": [20, 21, 20, 19],
    "Marks": [85, 91, 85, 76]
})

print(df)

     Name  Age  Marks
0  Manish   20     85
1   Rahul   21     91
2  Manish   20     85
3     Anu   19     76

In [141]:
print(df.drop_duplicates())

     Name  Age  Marks
0  Manish   20     85
1   Rahul   21     91
3     Anu   19     76

In [142]:
print(df)

     Name  Age  Marks
0  Manish   20     85
1   Rahul   21     91
2  Manish   20     85
3     Anu   19     76

In [143]:
df.duplicated()

0    False
1    False
2     True
3    False
dtype: bool

In [144]:
df = df.drop_duplicates()

In [145]:
print(df)

     Name  Age  Marks
0  Manish   20     85
1   Rahul   21     91
3     Anu   19     76

In [146]:
df["Name"] = df["Name"].replace("Anu","Anushree")
print(df)

       Name  Age  Marks
0    Manish   20     85
1     Rahul   21     91
3  Anushree   19     76

In [147]:
# Topic 5 — Changing Data Types
# Sometimes a column has the wrong data type.
# Example:
# df["Age"].dtype

df["Age"].dtype

dtype('int64')

In [148]:
print(df)

       Name  Age  Marks
0    Manish   20     85
1     Rahul   21     91
3  Anushree   19     76

In [149]:
df["Age"] = df["Age"].astype(float)
print(df)

       Name   Age  Marks
0    Manish  20.0     85
1     Rahul  21.0     91
3  Anushree  19.0     76

In [150]:
df["Age"].dtype

dtype('float64')

In [151]:
df["Age"] = df["Age"].astype(int)
print(df)

       Name  Age  Marks
0    Manish   20     85
1     Rahul   21     91
3  Anushree   19     76

In [152]:
df["Age"].dtype

dtype('int64')

In [153]:
df = pd.DataFrame({
    "Name": ["Manish", "Rahul", "Anu"],
    "Age": [20, -5, 19],
    "Marks": [85, 91, 76]
})

print(df)

# Replace -5 in Age with 21.
# Convert Age to integer using astype(int).
# Print the DataFrame

     Name  Age  Marks
0  Manish   20     85
1   Rahul   -5     91
2     Anu   19     76

In [154]:
df["Age"] = df["Age"].replace(-5,21)

print(df)

df["Age"].dtype

     Name  Age  Marks
0  Manish   20     85
1   Rahul   21     91
2     Anu   19     76

dtype('int64')

In [155]:
# String Cleaning with .str

# " Manish " → extra spaces
# "RAHUL" → uppercase
# " anu " → extra spaces + lowercase

df = pd.DataFrame({
    "Name": [" Manish ", "RAHUL", " anu ", "Kiran"]
})

print(df)

       Name
0   Manish
1     RAHUL
2      anu
3     Kiran

In [156]:
# Remove extra spaces — .str.strip()

df["Name"] = df["Name"].str.strip()
print(df)

     Name
0  Manish
1   RAHUL
2     anu
3   Kiran

In [157]:
# Convert to lowercase — .str.lower()

df["Name"] = df["Name"].str.lower()
print(df)

     Name
0  manish
1   rahul
2     anu
3   kiran

In [158]:
#Upper

df["Name"] = df["Name"].str.upper()
print(df)

     Name
0  MANISH
1   RAHUL
2     ANU
3   KIRAN

In [159]:
# Clean this DataFrame in the following order:
# 1. Clean the names
# Remove extra spaces and make all names lowercase.

# 2. Fix the incorrect age
# Replace -5 with 22.

# 3. Fill missing ages
# Fill missing Age values with 20.

# 4. Fill missing marks
# Fill missing Marks with 0.

# 5. Remove duplicate rows

# 6. Print the final cleaned DataFrame

import pandas as pd

df = pd.DataFrame({
    "Name": [" Manish ", "RAHUL", " Anu", "RAHUL", "Kiran "],
    "Age": [20, None, 19, None, -5],
    "Marks": [85, 91, None, 91, 88]
})

print(df)

       Name   Age  Marks
0   Manish   20.0   85.0
1     RAHUL   NaN   91.0
2       Anu  19.0    NaN
3     RAHUL   NaN   91.0
4    Kiran   -5.0   88.0

In [160]:
df["Name"] = df["Name"].str.strip()
df["Name"] = df["Name"].str.lower()
print(df)

     Name   Age  Marks
0  manish  20.0   85.0
1   rahul   NaN   91.0
2     anu  19.0    NaN
3   rahul   NaN   91.0
4   kiran  -5.0   88.0

In [161]:
df["Age"] = df["Age"].replace(-5,22)
print(df)

     Name   Age  Marks
0  manish  20.0   85.0
1   rahul   NaN   91.0
2     anu  19.0    NaN
3   rahul   NaN   91.0
4   kiran  22.0   88.0

In [162]:
df["Age"] = df["Age"].fillna(20)
df["Marks"] = df["Marks"].fillna(0)
print(df)

     Name   Age  Marks
0  manish  20.0   85.0
1   rahul  20.0   91.0
2     anu  19.0    0.0
3   rahul  20.0   91.0
4   kiran  22.0   88.0

In [163]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
dtype: bool

In [164]:
df = df.drop_duplicates()
print(df)

     Name   Age  Marks
0  manish  20.0   85.0
1   rahul  20.0   91.0
2     anu  19.0    0.0
4   kiran  22.0   88.0